// Runtime configuration - loaded from /config.json at app startup.
// config.json is generated by CDK deploy Lambda with the actual API URL.
// This avoids hardcoding URLs and eliminates the need to rebuild on URL changes.

let _config = null;

export async function loadConfig() {
  if (_config) return _config;
  try {
    const resp = await fetch('/config.json');
    _config = await resp.json();
  } catch (e) {
    console.warn('Failed to load /config.json, using fallback env vars:', e);
    _config = {};
  }
  return _config;
}

export function getApiBase() {
  const base = _config?.REACT_APP_API_BASE || process.env.REACT_APP_API_BASE || '';
  return base.replace(/\/$/, '');
}

export function getAccountId() {
  return _config?.REACT_APP_AWS_ACCOUNT_ID || process.env.REACT_APP_AWS_ACCOUNT_ID || '';
}

export function getRegion() {
  return _config?.REACT_APP_AWS_REGION || process.env.REACT_APP_AWS_REGION || 'us-east-1';
}

export function getUserPoolId() {
  return _config?.REACT_APP_USER_POOL_ID || process.env.REACT_APP_USER_POOL_ID || '';
}

export function getUserPoolClientId() {
  return _config?.REACT_APP_USER_POOL_CLIENT_ID || process.env.REACT_APP_USER_POOL_CLIENT_ID || '';
}
