import React from 'react';
import {
  Modal,
  Box,
  SpaceBetween,
  Button,
  Header,
  Container
} from '@cloudscape-design/components';

const SummaryV2Modal = ({ visible, onDismiss, summaryData }) => {

  // Parse the body if it's a string and get the summary content
  const getSummaryContent = () => {
    if (!summaryData) return 'No analysis data available';
    
    try {
      // axios parses JSON automatically → summaryData.summary
      // raw API Gateway response → summaryData.body (string)
      let summary = summaryData.summary;
      if (!summary && summaryData.body) {
        const parsedBody = typeof summaryData.body === 'string' ? JSON.parse(summaryData.body) : summaryData.body;
        summary = parsedBody?.summary;
      }
      
      if (!summary) return 'No summary data found';
      
      // Convert the summary object to beautifully formatted markdown text
      let content = '';
      
      // Add header with decorative line
      content += `═══════════════════════════════════════════════════════════════════════════════\n`;
      content += `                          MYSQL UPGRADE ANALYSIS REPORT\n`;
      content += `═══════════════════════════════════════════════════════════════════════════════\n\n`;
      
      if (summary.executive_summary) {
        content += `🔍 EXECUTIVE SUMMARY\n`;
        content += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
        content += `${summary.executive_summary}\n\n`;
      }
      
      if (summary.risk_assessment && Array.isArray(summary.risk_assessment)) {
        content += `⚠️  RISK ASSESSMENT\n`;
        content += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
        summary.risk_assessment.forEach(item => {
          if (item && item.trim()) {
            content += `  • ${item}\n`;
          }
        });
        content += '\n';
      }
      
      if (summary.remediation_steps && Array.isArray(summary.remediation_steps)) {
        content += `🔧 REMEDIATION STEPS\n`;
        content += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
        let stepNumber = 1;
        summary.remediation_steps.forEach((step) => {
          if (step && step.trim()) {
            if (step.includes('```')) {
              content += `${step}\n`;
            } else {
              content += `  ${stepNumber}. ${step}\n`;
              stepNumber++;
            }
          }
        });
        content += '\n';
      }
      
      if (summary.upgrade_strategy && Array.isArray(summary.upgrade_strategy)) {
        content += `🚀 UPGRADE STRATEGY\n`;
        content += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
        summary.upgrade_strategy.forEach(item => {
          if (item && item.trim()) {
            content += `  • ${item}\n`;
          }
        });
        content += '\n';
      }
      
      if (summary.timeline_sequence && Array.isArray(summary.timeline_sequence)) {
        content += `⏰ TIMELINE & SEQUENCE\n`;
        content += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
        summary.timeline_sequence.forEach(item => {
          if (item && item.trim()) {
            content += `  • ${item}\n`;
          }
        });
        content += '\n';
      }
      
      if (summary.post_upgrade_verification && Array.isArray(summary.post_upgrade_verification)) {
        content += `✅ POST-UPGRADE VERIFICATION\n`;
        content += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
        summary.post_upgrade_verification.forEach(item => {
          if (item && item.trim()) {
            content += `${item}\n`;
          }
        });
        content += '\n';
      }
      
      if (summary.risk_level) {
        content += `📊 OVERALL RISK LEVEL\n`;
        content += `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`;
        const riskEmoji = summary.risk_level.toLowerCase() === 'high' ? '🔴' : 
                         summary.risk_level.toLowerCase() === 'medium' ? '🟡' : '🟢';
        content += `  ${riskEmoji} ${summary.risk_level.toUpperCase()} RISK\n\n`;
      }
      
      // Add footer
      content += `═══════════════════════════════════════════════════════════════════════════════\n`;
      content += `                    Generated by MySQL Upgrader AI Assistant\n`;
      content += `═══════════════════════════════════════════════════════════════════════════════`;
      
      return content;
      
    } catch (error) {
      return `Error parsing response: ${error.message}`;
    }
  };

  const summaryContent = getSummaryContent();

  // Function to clean up inconsistent numbering
  const cleanupNumbering = (text) => {
    return text
      // Fix patterns like "1. Backup Creation\n  2. aws rds..." -> "1. Backup Creation\n     aws rds..."
      .replace(/^(\d+\.\s+[^\n]+)\n\s+(\d+\.\s+)/gm, '$1\n     ')
      // Fix patterns like "2. Storage Engine Migration\n  4. ALTER TABLE..." -> "2. Storage Engine Migration\n     ALTER TABLE..."
      .replace(/^(\d+\.\s+[^\n]+)\n\s+(\d+\.\s+)(ALTER|SELECT|SHOW|CREATE|DROP|INSERT|UPDATE|DELETE|aws|--)/gm, '$1\n     $3')
      // Remove standalone numbers before code lines
      .replace(/^\s*(\d+)\.\s+(ALTER|SELECT|SHOW|CREATE|DROP|INSERT|UPDATE|DELETE|aws|--)/gm, '     $2')
      // Clean up any remaining double numbering
      .replace(/^\s*\d+\.\s*(\d+\.)/gm, '$1');
  };

  return (
    <Modal
      onDismiss={onDismiss}
      visible={visible}
      size="max"
      header={
        <Header
          variant="h2"
          description="AI-powered analysis with comprehensive insights and recommendations"
        >
          🤖 AI Analysis & Recommendations
        </Header>
      }
      footer={
        <Box float="right">
          <SpaceBetween direction="horizontal" size="xs">
            <Button variant="primary" onClick={onDismiss}>
              Close
            </Button>
          </SpaceBetween>
        </Box>
      }
    >
      <Container
        header={
          <Header variant="h3">
            MySQL Upgrade Analysis Report
          </Header>
        }
      >
        <div style={{ 
          whiteSpace: 'pre-wrap',
          fontFamily: 'Monaco, Consolas, "Courier New", monospace',
          fontSize: '13px',
          lineHeight: '1.4',
          margin: 0,
          padding: '20px',
          backgroundColor: '#1e1e1e',
          color: '#f8f8f2',
          borderRadius: '8px',
          border: '1px solid #444',
          overflow: 'auto',
          maxHeight: '70vh'
        }}>
          {cleanupNumbering(summaryContent).split(/\n/).map((line, index) => {
            // Code blocks
            if (line.startsWith('```') || line.endsWith('```')) {
              return null; // Handle these separately
            }
            
            // Section headers with emojis and lines
            if (line.match(/^[🔍⚠️🔧🚀⏰✅📊]/)) {
              return (
                <div key={index} style={{
                  fontSize: '16px',
                  fontWeight: 'bold',
                  color: '#4fd1c7',
                  marginTop: '20px',
                  marginBottom: '10px'
                }}>
                  {line}
                </div>
              );
            }
            
            // Decorative lines
            if (line.match(/^━+$/)) {
              return (
                <div key={index} style={{
                  borderBottom: '2px solid #4a5568',
                  marginBottom: '15px',
                  height: '1px'
                }}>
                </div>
              );
            }
            
            // Phase headers (• Phase 1:, • Phase 2:, etc.)
            if (line.match(/^\s*•\s*Phase\s+\d+:/)) {
              return (
                <div key={index} style={{
                  backgroundColor: '#553c9a',
                  padding: '10px 15px',
                  margin: '8px 0 4px 0',
                  borderLeft: '4px solid #9f7aea',
                  borderRadius: '6px',
                  fontWeight: 'bold',
                  fontSize: '14px',
                  color: '#e9d8fd'
                }}>
                  {line.replace(/^\s*•\s*/, '📅 ')}
                </div>
              );
            }
            
            // Main bullet points (• items that aren't phases)
            if (line.match(/^\s*•/) && !line.match(/Phase\s+\d+:/)) {
              return (
                <div key={index} style={{
                  backgroundColor: '#2a4365',
                  padding: '8px 12px',
                  margin: '4px 0',
                  borderLeft: '4px solid #4fd1c7',
                  borderRadius: '4px'
                }}>
                  {line.replace(/^\s*•\s*/, '▸ ')}
                </div>
              );
            }
            
            // Numbered items (1., 2., etc.)
            if (line.match(/^\s*\d+\./)) {
              return (
                <div key={index} style={{
                  backgroundColor: '#2d3748',
                  padding: '8px 12px',
                  margin: '4px 0',
                  borderLeft: '4px solid #68d391',
                  borderRadius: '4px',
                  fontWeight: 'bold'
                }}>
                  {line}
                </div>
              );
            }
            
            // Sub-items (indented items under main points)
            if (line.match(/^\s{2,}•/) || line.match(/^\s{2,}\w/)) {
              return (
                <div key={index} style={{
                  backgroundColor: '#1a202c',
                  padding: '6px 16px',
                  margin: '2px 0 2px 20px',
                  borderLeft: '2px solid #718096',
                  borderRadius: '3px',
                  fontSize: '12px'
                }}>
                  ◦ {line.trim()}
                </div>
              );
            }
            
            // Regular text
            return <div key={index}>{line}</div>;
          })}
        </div>
      </Container>
    </Modal>
  );
};

export default SummaryV2Modal;
